### ISSUE TITLE
Exception is thrown by reading POM for jakarta.mail-api

### ISSUE THREAD

**Issue by liquidz** [liquidz/antq#166]
https://repo1.maven.org/maven2/jakarta/mail/jakarta.mail-api/2.0.1/jakarta.mail-api-2.0.1.pom

```
org.codehaus.plexus.util.xml.pull.XmlPullParserException: UTF-8 BOM plus xml decl of iso-8859-1 is incompatible (position: START_DOCUMENT seen <?xml version="1.0" encoding="iso-8859-1"... @1:41)
        at org.codehaus.plexus.util.xml.pull.MXParser.parseXmlDeclWithVersion(MXParser.java:3366)
        at org.codehaus.plexus.util.xml.pull.MXParser.parseXmlDecl(MXParser.java:3288)
        at org.codehaus.plexus.util.xml.pull.MXParser.parsePI(MXParser.java:3140)
        at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog(MXParser.java:1828)
        at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1757)
        at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1375)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:3876)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:595)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:609)
        at antq.util.maven$read_pom_STAR_.invokeStatic(maven.clj:129)
        at antq.util.maven$read_pom_STAR_.invoke(maven.clj:125)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at antq.util.async$fn_with_timeout$fn__13117$fn__13118.invoke(async.clj:14)
        at clojure.core.async$thread_call$fn__9187.invoke(async.clj:484)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by liquidz** [comment]
Fixed by #167
