### ISSUE TITLE
GitHub dependencies Action no longer functional after fix for issue #24

### ISSUE THREAD

**Issue by pmonks** [liquidz/antq#26]
The fix for issue #24 has resulted in the GitHub `dependencies` Action no longer functioning.  The specific error is:
```
2020-08-31T19:29:05.5020389Z ##[section]Starting: Request a runner to run this job

---------- 8< ----------

2020-08-31T19:29:35.8782521Z ##[group]Run java -jar /tmp/antq/antq.jar --error-format="::error file={{file}}::{{message}}"
2020-08-31T19:29:35.8782782Z [36;1mjava -jar /tmp/antq/antq.jar --error-format="::error file={{file}}::{{message}}"[0m
2020-08-31T19:29:35.8784800Z shell: sh -e {0}
2020-08-31T19:29:35.8784933Z ##[endgroup]
2020-08-31T19:29:37.5381586Z SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2020-08-31T19:29:37.5382524Z SLF4J: Defaulting to no-operation (NOP) logger implementation
2020-08-31T19:29:37.5382823Z SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2020-08-31T19:29:38.9251873Z Exception in thread "main" java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.io.IOException: Cannot run program "git": error=2, No such file or directory
2020-08-31T19:29:38.9274667Z 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
2020-08-31T19:29:38.9278790Z 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
2020-08-31T19:29:38.9282490Z 	at clojure.core$deref_future.invokeStatic(core.clj:2300)
2020-08-31T19:29:38.9292377Z 	at clojure.core$future_call$reify__8454.deref(core.clj:6974)
2020-08-31T19:29:38.9297238Z 	at clojure.core$deref.invokeStatic(core.clj:2320)
2020-08-31T19:29:38.9302237Z 	at clojure.core$pmap$step__8467$fn__8471.invoke(core.clj:7025)
2020-08-31T19:29:38.9307154Z 	at clojure.lang.LazySeq.sval(LazySeq.java:42)
2020-08-31T19:29:38.9307620Z 	at clojure.lang.LazySeq.seq(LazySeq.java:51)
2020-08-31T19:29:38.9308055Z 	at clojure.lang.RT.seq(RT.java:535)
2020-08-31T19:29:38.9308308Z 	at clojure.core$seq__5402.invokeStatic(core.clj:137)
2020-08-31T19:29:38.9308559Z 	at clojure.core$map$fn__5866.invoke(core.clj:2746)
2020-08-31T19:29:38.9308822Z 	at clojure.lang.LazySeq.sval(LazySeq.java:42)
2020-08-31T19:29:38.9309060Z 	at clojure.lang.LazySeq.seq(LazySeq.java:51)
2020-08-31T19:29:38.9309296Z 	at clojure.lang.RT.seq(RT.java:535)
2020-08-31T19:29:38.9309550Z 	at clojure.core$seq__5402.invokeStatic(core.clj:137)
2020-08-31T19:29:38.9309795Z 	at clojure.core$filter$fn__5893.invoke(core.clj:2809)
2020-08-31T19:29:38.9310037Z 	at clojure.lang.LazySeq.sval(LazySeq.java:42)
2020-08-31T19:29:38.9310290Z 	at clojure.lang.LazySeq.seq(LazySeq.java:51)
2020-08-31T19:29:38.9310526Z 	at clojure.lang.Cons.next(Cons.java:39)
2020-08-31T19:29:38.9310858Z 	at clojure.lang.RT.length(RT.java:1784)
2020-08-31T19:29:38.9339888Z 	at clojure.lang.RT.seqToArray(RT.java:1725)
2020-08-31T19:29:38.9340411Z 	at clojure.lang.LazySeq.toArray(LazySeq.java:132)
2020-08-31T19:29:38.9356889Z 	at clojure.lang.RT.toArray(RT.java:1698)
2020-08-31T19:29:38.9357259Z 	at clojure.core$to_array.invokeStatic(core.clj:344)
2020-08-31T19:29:38.9357509Z 	at clojure.core$sort.invokeStatic(core.clj:3113)
2020-08-31T19:29:38.9357742Z 	at clojure.core$sort.invoke(core.clj:3102)
2020-08-31T19:29:38.9358003Z 	at antq.report.format$fn__1706.invokeStatic(format.clj:25)
2020-08-31T19:29:38.9358279Z 	at antq.report.format$fn__1706.invoke(format.clj:20)
2020-08-31T19:29:38.9358520Z 	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
2020-08-31T19:29:38.9358775Z 	at antq.core$_main.invokeStatic(core.clj:112)
2020-08-31T19:29:38.9358999Z 	at antq.core$_main.doInvoke(core.clj:103)
2020-08-31T19:29:38.9359222Z 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
2020-08-31T19:29:38.9360151Z 	at antq.core.main(Unknown Source)
2020-08-31T19:29:38.9360493Z Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Cannot run program "git": error=2, No such file or directory
2020-08-31T19:29:38.9361065Z 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
2020-08-31T19:29:38.9361319Z 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
2020-08-31T19:29:38.9361559Z 	at clojure.core$deref_future.invokeStatic(core.clj:2300)
2020-08-31T19:29:38.9361800Z 	at clojure.core$future_call$reify__8454.deref(core.clj:6974)
2020-08-31T19:29:38.9362033Z 	at clojure.core$deref.invokeStatic(core.clj:2320)
2020-08-31T19:29:38.9362397Z 	at clojure.core$pmap$step__8467$fn__8471.invoke(core.clj:7025)
2020-08-31T19:29:38.9362647Z 	at clojure.lang.LazySeq.sval(LazySeq.java:42)
2020-08-31T19:29:38.9362861Z 	at clojure.lang.LazySeq.seq(LazySeq.java:51)
2020-08-31T19:29:38.9363088Z 	at clojure.lang.Cons.next(Cons.java:39)
2020-08-31T19:29:38.9363311Z 	at clojure.lang.RT.next(RT.java:713)
2020-08-31T19:29:38.9363538Z 	at clojure.core$next__5386.invokeStatic(core.clj:64)
2020-08-31T19:29:38.9363770Z 	at clojure.core$some.invokeStatic(core.clj:2701)
2020-08-31T19:29:38.9364003Z 	at clojure.core$some.invoke(core.clj:2692)
2020-08-31T19:29:38.9364501Z 	at antq.core$complete_versions_by.invokeStatic(core.clj:69)
2020-08-31T19:29:38.9364848Z 	at antq.core$complete_versions_by.invoke(core.clj:67)
2020-08-31T19:29:38.9365082Z 	at antq.core$outdated_deps$fn__3097.invoke(core.clj:85)
2020-08-31T19:29:38.9365318Z 	at clojure.core$pmap$fn__8462$fn__8463.invoke(core.clj:7022)
2020-08-31T19:29:38.9365563Z 	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
2020-08-31T19:29:38.9365797Z 	at clojure.lang.AFn.call(AFn.java:18)
2020-08-31T19:29:38.9366029Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-08-31T19:29:38.9366259Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
2020-08-31T19:29:38.9366517Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
2020-08-31T19:29:38.9366763Z 	at java.base/java.lang.Thread.run(Thread.java:832)
2020-08-31T19:29:38.9367016Z Caused by: java.io.IOException: Cannot run program "git": error=2, No such file or directory
2020-08-31T19:29:38.9367267Z 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
2020-08-31T19:29:38.9367509Z 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
2020-08-31T19:29:38.9367744Z 	at java.base/java.lang.Runtime.exec(Runtime.java:590)
2020-08-31T19:29:38.9367974Z 	at clojure.java.shell$sh.invokeStatic(shell.clj:113)
2020-08-31T19:29:38.9368207Z 	at clojure.java.shell$sh.doInvoke(shell.clj:79)
2020-08-31T19:29:38.9368435Z 	at clojure.lang.RestFn.invoke(RestFn.java:436)
2020-08-31T19:29:38.9368664Z 	at antq.ver.git$git_ls_remote.invokeStatic(git.clj:18)
2020-08-31T19:29:38.9368913Z 	at antq.ver.git$git_ls_remote.invoke(git.clj:16)
2020-08-31T19:29:38.9369140Z 	at antq.ver.git$fn__2606.invokeStatic(git.clj:23)
2020-08-31T19:29:38.9369365Z 	at antq.ver.git$fn__2606.invoke(git.clj:20)
2020-08-31T19:29:38.9369578Z 	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
2020-08-31T19:29:38.9369810Z 	at antq.core$assoc_versions.invokeStatic(core.clj:44)
2020-08-31T19:29:38.9370036Z 	at antq.core$assoc_versions.invoke(core.clj:42)
2020-08-31T19:29:38.9370258Z 	... 7 more
2020-08-31T19:29:38.9370484Z Caused by: java.io.IOException: error=2, No such file or directory
2020-08-31T19:29:38.9370722Z 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
2020-08-31T19:29:38.9370958Z 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
2020-08-31T19:29:38.9371196Z 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:250)
2020-08-31T19:29:38.9371435Z 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
2020-08-31T19:29:38.9371663Z 	... 19 more
2020-08-31T19:30:39.0697260Z ##[error]Process completed with exit code 1.

---------- 8< ----------
```

Sorry for not thinking to test this until now!

**Comment by pmonks** [comment]
BTW I'm googling how to ensure `git` is installed in a GitHub Action container - will report back with my findings.

**Comment by liquidz** [comment]
@pmonks Thanks for your reporting and contribution!

I created a new tag `0.7.1`, so dockerhub will start building soon.
https://hub.docker.com/r/uochan/antq/builds
(It seems `latest` tag is already built)

**Comment by pmonks** [comment]
Awesome!  Tested it out, and it appears to be working great now.
